# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_editar_juegos.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 20, 311, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 13pt \"MV Boli\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 100, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 10pt \"MV Boli\";")
        self.label_2.setObjectName("label_2")
        self.entrada_nombre_juego = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_nombre_juego.setGeometry(QtCore.QRect(290, 100, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entrada_nombre_juego.setFont(font)
        self.entrada_nombre_juego.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_nombre_juego.setObjectName("entrada_nombre_juego")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 210, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 10pt \"MV Boli\";\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.entrada_precio_juego = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_precio_juego.setGeometry(QtCore.QRect(290, 210, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entrada_precio_juego.setFont(font)
        self.entrada_precio_juego.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_precio_juego.setText("")
        self.entrada_precio_juego.setObjectName("entrada_precio_juego")
        self.boton_guardar_cambios_juego = QtWidgets.QPushButton(self.centralwidget)
        self.boton_guardar_cambios_juego.setGeometry(QtCore.QRect(270, 280, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boton_guardar_cambios_juego.setFont(font)
        self.boton_guardar_cambios_juego.setStyleSheet("font: 10pt \"MV Boli\";")
        self.boton_guardar_cambios_juego.setObjectName("boton_guardar_cambios_juego")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 10pt \"MV Boli\";")
        self.label_6.setObjectName("label_6")
        self.entrada_tipo_plataforma = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_tipo_plataforma.setGeometry(QtCore.QRect(290, 140, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entrada_tipo_plataforma.setFont(font)
        self.entrada_tipo_plataforma.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_tipo_plataforma.setText("")
        self.entrada_tipo_plataforma.setObjectName("entrada_tipo_plataforma")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 70, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 10pt \"MV Boli\";")
        self.label_7.setObjectName("label_7")
        self.entrada_tipo_juego = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_tipo_juego.setGeometry(QtCore.QRect(290, 70, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entrada_tipo_juego.setFont(font)
        self.entrada_tipo_juego.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_tipo_juego.setText("")
        self.entrada_tipo_juego.setObjectName("entrada_tipo_juego")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 170, 51, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 10pt \"MV Boli\";")
        self.label_8.setObjectName("label_8")
        self.entrada_anio_juego = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_anio_juego.setGeometry(QtCore.QRect(290, 170, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entrada_anio_juego.setFont(font)
        self.entrada_anio_juego.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_anio_juego.setText("")
        self.entrada_anio_juego.setObjectName("entrada_anio_juego")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Introduce los nuevos datos del juego"))
        self.label_2.setText(_translate("MainWindow", "Nombre Juego:"))
        self.label_5.setText(_translate("MainWindow", "Precio:"))
        self.boton_guardar_cambios_juego.setText(_translate("MainWindow", "GUARDAR CAMBIOS"))
        self.label_6.setText(_translate("MainWindow", "Plataforma:"))
        self.label_7.setText(_translate("MainWindow", "Tipo de Juego:"))
        self.label_8.setText(_translate("MainWindow", "Año:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
